### ISSUE TITLE
Query relating to level

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/talk-like-a-pirate#8]
talk-like-a-pirate | URL: /en/projects/talk-like-a-pirate/10 Is this really 'Builder' level? Totally fine for this level up to RegEx - then a bit scary for a non programmer. - Rosa :) | 2019-02-07 11:02:42.019859
-- | -- | --

from @rosalanghammer

**Comment by MarcScott** [comment]
@PhilipHarney Could you review and pick a new level if you think it is warranted

**Comment by PhilipHarney** [comment]
I think, if we consider regex to be somewhat equivalent to an additional external library — which it is in new terms and syntax to learn, even if not strictly in code — then we can easily say it's developer level based on 'Can effectively combine functionality from multiple libraries or APIs and refer to documentation'. Bumping it up accordingly.
